### ISSUE TITLE
Application page cannot be served

### ISSUE THREAD

**Issue by BJCaasenbrood** [LucMarechal/Soft-Robotics-Materials-Database#10]
Hi,

I noticed the Herokuapp application page is down, and got the following message:

![image](https://user-images.githubusercontent.com/36262141/213157279-0edac9c8-56c1-4663-ab2f-042c6a194857.png)

Any chance this can be fixed easily?

**Comment by LucMarechal** [comment]
The App is now deployed here : https://soro-materials-database.onrender.com

**Comment by LucMarechal** [comment]
The App is now deployed here : https://soro-materials-database.onrender.com/
